[package]
name = "limitador"
version = "0.2.0"
authors = ["David Ortiz <z.david.ortiz@gmail.com>"]
license = "Apache-2.0"
description = "Rate limiter."
homepage = "https://github.com/kuadrant/limitador"
repository = "https://github.com/kuadrant/limitador"
documentation = "https://docs.rs/limitador"
edition = "2018"

# We make redis and infinispan optional to be able to compile for wasm32.
[features]
default = ["redis_storage"]
redis_storage = ["redis", "r2d2", "tokio"]
infinispan_storage = ["infinispan", "reqwest", "openssl"]

[dependencies]
ttl_cache = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
futures = "0.3"
async-trait = "0.1"
cfg-if = "1"
prometheus = "0.13"
lazy_static = "1"

# Optional dependencies
redis = { version = "0.21", optional = true, features = ["connection-manager"] }
r2d2 = { version = "0.8", optional = true }
tokio = { version = "1", optional = true, features = ["full"] }
infinispan = { version = "0.2", optional = true }
reqwest = { version = "0.11", optional = true }

# reqwest dependency. Needed here to avoid problems when compiling
openssl = { version = "0.10", optional = true, features = ["vendored"] }

[dev-dependencies]
serial_test = "0.5"
criterion = "0.3"
paste = "1"
rand = "0.8"
tokio = { version = "1", features = ["full"]  } # wasm_storage tests use tokio::test

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
